name = "zero-nav"
account_id = "22788d96116325ff531105e98c23bc95"
main = "src/index.ts"
compatibility_date = "2025-11-20"

[[kv_namespaces]]
binding = "BOOKMARKS_KV"
id = "bb118ee538a04aafbd60995912677f8c"

[[rules]]
type = "Text"
globs = ["**/*.css", "**/*.client.js"]
fallthrough = true

[env.production]
name = "zero-nav"
main = "src/index.ts"
compatibility_date = "2025-11-20"
account_id = "22788d96116325ff531105e98c23bc95"

[[env.production.kv_namespaces]]
binding = "BOOKMARKS_KV"
id = "bb118ee538a04aafbd60995912677f8c"

[[env.production.rules]]
type = "Text"
globs = ["**/*.css", "**/*.client.js"]
fallthrough = true
