name = "zero-nav-next"
account_id = "22788d96116325ff531105e98c23bc95"
main = ".open-next/worker.js"
compatibility_date = "2025-11-20"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "BOOKMARKS_KV"
id = "bb118ee538a04aafbd60995912677f8c"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[env.production]
name = "zero-nav-next"
compatibility_date = "2025-11-20"
compatibility_flags = ["nodejs_compat"]
account_id = "22788d96116325ff531105e98c23bc95"

[[env.production.kv_namespaces]]
binding = "BOOKMARKS_KV"
id = "bb118ee538a04aafbd60995912677f8c"

[env.production.assets]
directory = ".open-next/assets"
binding = "ASSETS"
